---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /NAS/Media/Komiksy:/Komiksy
      - /NAS/Media/Manga:/Manga
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - kavita
networks:
  kavita:
    name: kavita_network
