---
services:
  kavita:
    image: linuxserver/kavita:0.8.1
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /NAS/Media/Komiksy:/Komiksy
      - /NAS/Media/Manga:/Manga
    ports:
      - 8083:5000
    restart: no
    networks:
      - kavita
networks:
  kavita:
    name: kavita_network
