services:
  qbittorrent:
#    image: lscr.io/linuxserver/qbittorrent:latest
    image: kasmweb/qbittorrent:1.15.0
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8888
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /NAS/downloads:/downloads
      - /NAS/Media:/Media
    ports:
      - 8888:8888
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - qbittorrent
networks:
  qbittorrent:
    name: qbittorrent_network
