services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8888
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /NAS/downloads:/downloads
      - /NAS/Media:/Media
    ports:
      - 8084:8888
      - 6881:6881
      - 6881:6881/udp
    restart: no
    networks:
      - qbittorrent
networks:
  qbittorrent:
    name: qbittorrent_network
