#version: '3'
#
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:2024.4.4"
    ports:
      - 8123:8123
    volumes:
      - /var/docker/haos/config:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
#      - /dev/bus/usb/003/004:/dev/bus/usb/003/004
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    networks:
      - haos
networks:
  haos:
    name: haos_network
