services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - TZ
      - WEBPASSWORD
#      - REV_SERVER
#      - REV_SERVER_DOMAIN
#      - REV_SERVER_TARGET
#      - REV_SERVER_CIDR
      - VIRTUAL_HOST
      - WEBTHEME
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
