services:
  boinc:
    image: linuxserver/boinc:7.24.1
    container_name: boinc
#    command: sh -c "dpkg --add-architecture i386 && apt update && apt install libc6:i386 lib32z1 usbutils -y"
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
    volumes:
      - /path/to/data:/config
    ports:
      - 8081:8080
    restart: no
    networks:
      - boinc
    devices:
      - /dev/bus/usb/:/dev/bus/usb/
    privileged: false
networks:
  boinc:
    name: boinc_network

