---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:7.5.1 #latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
#      - PASSWORD= #optional
#      - CLI_ARGS= #optional
    volumes:
      - /NAS/Media/Calibre:/config/Biblioteka
      - ./config:/config
      - /NAS/Media/Ksiazki:/Ksiazki
    ports:
      - 8082:8080
#      - 8181:8181
#      - 8083:8081
    restart: unless-stopped
    networks:
      - calibre
networks:
  calibre:
    name: calibre_network
