services:
  mysql-fa:
    image: mysql:8.0
    hostname: mysql-fa
    container_name: mysql-fa
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql-fa:/var/lib/mysql
    networks:
      - wp-fa

  wordpress-fa:
    image: wordpress:6.5.4
    hostname: wordpress-fa
    container_name: wordpress-fa
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql-fa
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wp-fa:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8088:80
    networks:
      - wp-fa
    depends_on:
      - mysql-fa

networks:
  wp-fa:
    name: wp-fa_network
