services:
  jellyfin:
#    image: lscr.io/linuxserver/jellyfin:latest
    image: linuxserver/jellyfin:10.8.13
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.2 #optional
    volumes:
      - ./config:/config
      - /NAS/Media/Programy:/Programy
      - /NAS/Media/Filmy:/Filmy
      - /NAS/Media/Seriale:/Seriale
      - /NAS/Media/Anime:/Anime
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: no
    networks:
      - jellyfin
networks:
  jellyfin:
    name: jellyfin_network

