services:
  activepieces:
    image: activepieces/activepieces:0.27.0
    container_name: activepieces
    restart: no
    ports:
      - 8085:80
    depends_on:
      - postgres
      - redis
    env_file: .env
    networks:
      - activepieces
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME}'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - activepieces
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - activepieces
networks:
  activepieces:
    name: activepieces_network
